import fs from 'node:fs/promises';
import { parse } from 'acorn';
import { methods, publicMethods, studentMethods } from './methods.mjs';
const read = path => fs.readFile(path, 'utf8');
const source = await read('Code.gs');
const overrides = await read('cloudflare/google-overrides.js');
const replacementNames = new Set(parse(overrides, { ecmaVersion: 'latest' }).body.filter(n => n.type === 'FunctionDeclaration').map(n => n.id.name));
// Remove legacy web endpoints and replace unsafe initialization/auth in the generated target.
const removedNames = new Set([...replacementNames, 'doGet', 'doPost']);
let backend = source;
for (const node of parse(source, { ecmaVersion: 'latest' }).body.reverse()) {
  if (node.type === 'FunctionDeclaration' && removedNames.has(node.id.name)) backend = backend.slice(0, node.start) + backend.slice(node.end);
}
const exports = [...new Set([...methods, 'validateSession'])];
const bridge = await read('cloudflare/google-bridge.js');

// Prune everything the bridge cannot reach, so demo/seed/import helpers and their
// hardcoded defaults never exist in the deployed project.
// One-time installer, kept in its own file so it stays outside the RPC surface.
const bootstrapBody = await read('cloudflare/bootstrap.js');
const body = parse(backend, { ecmaVersion: 'latest' }).body;
const units = new Map();
for (const node of body) {
  if (node.type === 'FunctionDeclaration') units.set(node.id.name, backend.slice(node.start, node.end));
  else if (node.type === 'VariableDeclaration') for (const d of node.declarations) if (d.id.type === 'Identifier') units.set(d.id.name, backend.slice(node.start, node.end));
}
// Overrides are appended verbatim by the template below, so they are not units here.
// Helpers that must never reach the deployed project, even if referenced by name.
const forbidden = new Set(['doGet', 'doPost', 'setupSystem', 'loginDemoUser', 'ensureDemoUser', 'enableDemoMode',
  'disableDemoMode', 'clearDemoData', 'resetDemoData', 'initializeDemoData', 'initializeAdminUser',
  'initializeSheets', 'initializeDefaultSettings', 'initializeStudentRosterTemplate', 'ensureSampleStudentsExist',
  'clearOperationalData', 'runDiagnostics', 'syncDataFromGoogleDrive', 'myFunction',
  'testSubmitForm', 'cleanDuplicateRowsInSheet', 'addSyncSourceId', 'isSpreadsheetWritable']);
for (const name of forbidden) units.delete(name);
function referencesOf(code) {
  const names = new Set();
  const walk = node => {
    if (!node || typeof node !== 'object') return;
    if (Array.isArray(node)) return node.forEach(walk);
    if (node.type === 'Identifier') { names.add(node.name); return; }
    for (const key of Object.keys(node)) if (key !== 'start' && key !== 'end') walk(node[key]);
  };
  walk(parse(code, { ecmaVersion: 'latest' }));
  return names;
}
const kept = new Set();
const queue = [...new Set([...exports, ...publicMethods, ...studentMethods, 'hashPassword', 'writeAuditLog', ...referencesOf(overrides)])];
while (queue.length) {
  const name = queue.pop();
  if (kept.has(name) || !units.has(name)) continue;
  kept.add(name);
  referencesOf(units.get(name)).forEach(reference => queue.push(reference));
}
const providedByOverrides = new Set(parse(overrides, { ecmaVersion: 'latest' }).body.filter(n => n.type === 'FunctionDeclaration').map(n => n.id.name));
for (const name of exports) if (!kept.has(name) && !providedByOverrides.has(name)) throw new Error(`Exported method not found in source: ${name}`);
const dropped = [...units.keys()].filter(name => !kept.has(name));
backend = [...kept].map(name => units.get(name)).join('\n');
const generated = `// Generated by npm run build. Do not edit.\nconst Backend_ = (function () {\n${backend}\n${overrides}\nreturn {${exports.join(',')}};\n})();\nconst PUBLIC_METHODS_ = ${JSON.stringify(publicMethods)};\nconst STUDENT_METHODS_ = ${JSON.stringify(studentMethods)};\n${bridge}\n${bootstrapBody}`;
parse(generated, { ecmaVersion: 'latest' });
console.log(`Pruned ${dropped.length} unreachable helpers: ${dropped.join(', ')}`);
await fs.mkdir('dist/google', { recursive: true });
await fs.mkdir('dist/public', { recursive: true });
await fs.writeFile('dist/google/Backend.gs', generated);
await fs.copyFile('appsscript.json', 'dist/google/appsscript.json');
let html = await read('Index.html');
html = html.replace("<?!= include('Styles'); ?>", await read('Styles.html'))
  .replace("<?!= include('Scripts'); ?>", `<script src="/client.js"></script>\n${await read('Scripts.html')}`);
if (html.includes('<?')) throw new Error('Unresolved Apps Script template');
await fs.writeFile('dist/public/index.html', html);
await fs.copyFile('cloudflare/client.js', 'dist/public/client.js');
await fs.cp('assets', 'dist/public/assets', { recursive: true });
console.log('Built Cloudflare website and isolated Google bridge in dist/');
